### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by MinhWalker** [11dogzi/Comfyui-ergouzi-Nodes#8]
Traceback (most recent call last):
  File "C:\Working\ComfyUI_windows_portable\ComfyUI\[nodes.py](javascript:void(0);)", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in call_with_frames_removed
  File "C:\Working\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes_[init.py](javascript:void(0);)", line 57, in <module>
    from .nodes.EGDZXLJZ import SequentialImageLoader
  File "C:\Working\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\[EGDZXLJZ.py](javascript:void(0);)", line 5, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

Can you help me fix that? Tks you

**Comment by 11dogzi** [comment]
1. 安装  模块tkinter
tkinter 是Python的标准库模块，一般情况下会随Python一同安装。 如果你收到此错误，可能是因为你的Python环境中缺少此模块。

在Windows操作系统上，你可以尝试以下命令来安装  模块：tkinter

bash
复制代码
pip install python-tk
2. 确保使用的是正确的Python版本
有时候，可能是由于你使用的Python版本没有附带 tkinter 模块。在这种情况下，检查并安装一个新的Python版本，并确保在安装过程中选择安装 tkinter。

**Comment by metsweet999** [comment]
i tried and failed:
"E:\ComfyUI_Mini-2\python_embeded>python.exe -m pip install tkinter
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

E:\ComfyUI_Mini-2\python_embeded>python.exe -m pip install  python-tk
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement python-tk (from versions: none)
ERROR: No matching distribution found for python-tk
"

**Comment by metsweet999** [comment]
dear author, which version of python are u using?

**Comment by metsweet999** [comment]
dear author,
i doubt if there is any spelling mistake in the name of the module,
could u " pip list " ur installed modules and check if or not the name is correct?

**Comment by 11dogzi** [comment]
我也是第一次遇到您提出的这个问题，但是这个模块的确是python标准库的一部分，我使用的pyhon版本是Python 3.10.11

**Comment by metsweet999** [comment]
miy version :
"
E:\ComfyUI_Mini-1\python_embeded>python.exe --version
Python 3.11.6
"
i just don't like to downgrade it ,
many other extensions may rely on higher version of python,
if ergou could fix it this in python 3.11.6 or newer version, many people will be happy.

**Comment by q7793527** [comment]
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI\ComfyUI\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\__init__.py", line 57, in <module>
    from .nodes.EGDZXLJZ import SequentialImageLoader
  File "G:\ComfyUI\ComfyUI\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\EGDZXLJZ.py", line 5, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

Cannot import G:\ComfyUI\ComfyUI\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes module for custom nodes: No module named 'tkinter'
我也遇到了同样的问题，我的全局python环境有这个库，用的ComfyUI官方整合包，里面没有这个模块,从全局环境那边把tkinter库拷贝过来也是无法导入

**Comment by MinhWalker** [comment]
> Traceback (most recent call last): File "C:\Working\ComfyUI_windows_portable\ComfyUI[nodes.py](javascript:void(0);)", line 1941, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in call_with_frames_removed File "C:\Working\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes_init.py", line 57, in from .nodes.EGDZXLJZ import SequentialImageLoader File "C:\Working\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes[EGDZXLJZ.py](javascript:void(0);)", line 5, in import tkinter as tk ModuleNotFoundError: No module named 'tkinter'
> 
> Can you help me fix that? Tks you

Hi @q7793527 , @metsweet999 @11dogzi  I found the solution to resolve that on this link
https://stackoverflow.com/questions/37710205/python-embeddable-zip-install-tkinter

Issue from embedded python on comfyUI do not exist TKinter lib, I tried with pip install but not effect because TKinter is lib on buildin package of Python not side-package. So I tried to copy TKinter from my python on my system an It's WORKED. 

![image](https://github.com/user-attachments/assets/8d01db88-ad5d-406d-80d1-f92f1bdcff92)

**Comment by MinhWalker** [comment]
An error not from your repository so I will close that by this comment, I just push solution on previous comment. Thank your supoprt @11dogzi
