### ISSUE TITLE
Mask Expansion and Stitching node not working after ComfyUI update

### ISSUE THREAD

**Issue by Orenji-Tangerine** [11dogzi/Comfyui-ergouzi-Nodes#9]
As per title stated, the node Mask Expansion and Image Cropping Data Stitching stops working with error now, the input is there but it just cannot proceed with error.

![image](https://github.com/user-attachments/assets/0ecb4a84-7c7e-4149-8ede-cbc3c7fd0989)

![image](https://github.com/user-attachments/assets/93c5ea22-bfc4-4b8d-accc-e1fa1ea1b595)

![image](https://github.com/user-attachments/assets/636b9dee-fb63-4310-9e03-10c26de809a6)

**Comment by Orenji-Tangerine** [comment]
Just to show the input is there from the previous node with the following screenshot

![image](https://github.com/user-attachments/assets/73ff0350-7cba-4de0-b9f3-782857c7c79c)

**Comment by Orenji-Tangerine** [comment]
It works in the Chinese version though, I just tried.

**Comment by jasonliu0704** [comment]
> It works in the Chinese version though, I just tried.

which chinese version?

**Comment by Orenji-Tangerine** [comment]
> > It works in the Chinese version though, I just tried.
> 
> which chinese version?

The one mentioned in the model card README.md, URL link below
https://github.com/11dogzi/Comfyui-ergouzi-DGNJD

**Comment by jasonliu0704** [comment]
for some reason, I have to fix those node and reconnect to make them work
